pipeline {
    agent { label 'master-node1' }

    tools {
        maven 'Maven'
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('springbootapp') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('springbootapp') {
                    sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('springbootapp') {
                    sh 'mvn package'
                }
            }
        }
    }

    post {
        success {
            echo 'Build Successful on master-node1!'
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
        failure {
            echo 'Build Failed on master-node1!'
        }
    }
}
